### ISSUE TITLE
unclear how to use union types

### ISSUE THREAD

**Issue by mooreniemi** [kaiko-ai/typedspark#157]
I wanted to have a function accept a `Union[]` of `Schema`, but when I try that I hit this error:

```
TypeError: issubclass() arg 1 must be a class
```

Is there a way to express this?

**Comment by mooreniemi** [comment]
Where Schemas has columns in common and my function depends only on those columns in common, I'd like to be able to represent that interface. So the function literally can take `A` or `B` because both have say `.col` in common, and the function only operates on `.col`. Does that make sense?

**Comment by nanne-aben** [comment]
So something like this?

```python
class Person(Schema):
   name: Column[StringType]
   age: Column[IntegerType]

class Animal(Schema):
   type: Column[StringType]
   age: Column[StringType]

def birthday(df: Union[DataSet[Person], DataSet[Animal]]) ->  Union[DataSet[Person], DataSet[Animal]]:
    return transform_to_schema(
        df, 
        df.typedspark_schema, 
        {df.typedspark_schema.age: df.typedspark_schema.age + 1},
    )
```
Is that what you're looking for? If so, I might have some ideas on how to improve on the above snippet. If not, could you provide some example code to illustrate what you're looking for?
