### ISSUE TITLE
Idea: Schema code generator

### ISSUE THREAD

**Issue by farridav** [kaiko-ai/typedspark#23]
This project looks great, and might be what I'm missing on my projects, what would be great, to speed up adoption and integration, would be an interface we can use to generate stubs for schemas, given a spark dataframe as an input e.g:

```
from typedspark.helpers import generate_stubs


my_person_df = get_person()
print(generate_stubs(my_person_df))
```

This would really help on big projects with lots of data sources that need schemas (including mine)

**Comment by nanne-aben** [comment]
Thanks @farridav!

We actually do have something like that:
```python
from typedspark import load_table

df, Person = load_table(spark, "person_table")
Person
```

Which, when ran in a notebook, would output the inferred schema:
```python
from pyspark.sql.types import LongType, StringType
from typedspark import Column, Schema

class DynamicallyLoadedSchema(Schema):
    name: Column[StringType]
    age: Column[LongType]
```

For more options, have a look at:
https://typedspark.readthedocs.io/en/latest/databricks.html

Does that address your need?

And on a related note... I guess it's currently kinda hidden in the documentation (under `Using typedspark in Databricks notebooks`). Maybe we should consider renaming that part of the documentation.

**Comment by farridav** [comment]
Ah ha, I completely missed out on the advanced section of the docs.. I will give this a go immediately, it seems to fit my use case very well.

Thanks for all the hard work
