### ISSUE TITLE
DataSet.where and DataSet.filter inconsistent.

### ISSUE THREAD

**Issue by jromerosk** [kaiko-ai/typedspark#566]
Current behaviour

typedspark.DataSet.where returns a DataFrame
typedspark.DataSet.filter returns a DataSet

Expected behaviour:
They should both return a DataSet.

**Comment by nanne-aben** [comment]
Thanks @jromerosk !

Indeed, we haven't implemented this for `DataSet.where()` yet. Should be an easy change to make. 

* [] Update `DataSet`
* [] Update `DataSetImplements`
* [] Update [this page](https://typedspark.readthedocs.io/en/latest/advanced_linting_support.html) in the documentation

Would you be willing to make a contribution?

**Comment by jromerosk** [comment]
Yep sure

**Comment by jromerosk** [comment]
There you go.
https://github.com/kaiko-ai/typedspark/pull/567
