### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by mohitCodepy** [kaiko-ai/typedspark#60]
I would like to contribute on this organisation,
If you have any bugs or want the implementation of the feature then I'm available.

Thank you

**Comment by mohitCodepy** [comment]
@nanne-aben , 

Yes, I'm highly interested,
I would love to work on this, for clarification, I haven't worked on this, but I have a better understanding of Python and after reading and understanding the above detail I am able to understand it.
I'm ready to explore it more also Is there any public channel or group so we can communicate easily from there?

I'm a beginner to open source, but I have the potential to do complex stuff, also I'll need some help on this.
BTW thanks for your explanation, I'll try to reproduce it.

Thanks

**Comment by nanne-aben** [comment]
Great! Sure, happy to help!

I think Github Discussions would be a good place for this. I've enabled it for this repo, it should show up as a tab now. Does that work for you?

**Comment by mohitCodepy** [comment]
Yes, thank you, It is visible :smile:

**Comment by nanne-aben** [comment]
Hi mohitCodepy! How's it going? Do you need any help?

**Comment by mohitCodepy** [comment]
@nanne-aben , apologise for the inactivity, was busy in college work but I'm available now

**Comment by nanne-aben** [comment]
No worries, just checking!

Lemme know if I can help you with anything!

**Comment by nanne-aben** [comment]
Hi mohitCodepy! I needed to have this functionality for another project, so I implemented it in #172. Hope you don't mind me taking it of your hands!

**Comment by mohitCodepy** [comment]
> Hi mohitCodepy! I needed to have this functionality for another project, so I implemented it in #172. Hope you don't mind me taking it of your hands!

@nanne-aben 

I'm really sorry about that, 
can you please add me as a reviewer in #172 ?, so that I can also understand about the code.
Thanks

**Comment by nanne-aben** [comment]
I think you should be able to comment on the PR already, right? 

Lemme know if it doesn't work, then I'll dive into the settings a bit more.

**Comment by mohitCodepy** [comment]
@nanne-aben , Sure
